-w, --[no-]watch
name: CSS Resume Garden
description: A series of customixed Resume webpages inspired by CSS Garden.
google_analytics:
url: http://Drakenhart.github.io

permalink: /blog/:title.html

footer-links:
  dribble:
  email:
  facebook:
  flicker:
  github:
  instagram:
  linkedin:
  onintrest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
  
disqus:


markdown: kramdown
  
sass:
  style: :expanded #youmight prefer to minifiy using :compress
  
exclude:
  
timezone: America/New_York

gems: 
- jekyll-sitemap
- jekyll-feed

