name: "CSS Resume Garden"
description: "A series of customized Resume webpages inspired by CSS Garden."
google_analytics:
url: http://Drakenhart.github.io

sass:
  style: :expanded #youmight prefer to minifiy using :compress
  
  # Outputting
permalink:     /:title.html
paginate: 10
paginate_path: /page:num
timezone:      null

include: ['_pages']

# Where things are
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Footer
footer-links:
  dribble:
  email:
  facebook:
  flicker:
  github:
  instagram:
  linkedin:
  onintrest:
  rss:
  twitter: drakenhart
  stackoverflow:
  youtube:
  googleplus:
  
disqus:


  
exclude:
  
timezone: America/New_York

markdown: kramdown

 github: [metadata]
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-sitemap
  - jekyll-feed
