name: "CSS Resume Garden"
description: "A series of customized Resume webpages inspired by CSS Garden."
google_analytics:
url: http://Drakenhart.github.io

permalink: /blog/:title.html

footer-links:
  dribble:
  email:
  facebook:
  flicker:
  github:
  instagram:
  linkedin:
  onintrest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
  
disqus:

sass:
  style: :expanded #youmight prefer to minifiy using :compress
  
exclude:
  
timezone: America/New_York

markdown: kramdown

 github: [metadata]
 kramdown:
   input: GFM
   hard_wrap: false
 gems:
   - jekyll-coffeescript
   - jekyll-paginate
   - jekyll-sitemap
  - jekyll-feed
